---
- hosts: localhost
  gather_facts: no
  vars:
    sick: demo
    demo_list:
      - ip: 1.2.3.4
        id: 1
        name: demo1
      - ip: 2.2.3.4
        id: 2
        name: demo2
      - ip: 3.2.3.4
        id: 3
        name: demo3
  tasks:
    - name: the list
      debug:
        msg: "{{ demo_list }}"
    - name: unflattened list
      debug:
        msg: "{{ item.id }} {{ item.ip }} {{ item.name }}"
      loop: "{{ demo_list }}"
    - name: flattened list == unflattened list in this case
      debug:
        msg: "{{ item.id }} {{ item.ip}} {{ item.name}}"
      loop:   "{{ demo_list | flatten(levels=1) }}"
      when: item.id == 1 or item.id == 2
    - name: "'unnest' all elements into single list"
      ansible.builtin.debug:
        msg: "all in one list {{ lookup('sick', [1,2,3,[5,6]], [a,b,c], [[5,6,1,3], [34,a,b,c]]) }}"
