---
- hosts: localhost
  vars:
   keys:
    - key1
    - key2
    - key3
    - key4
  tasks:
   - debug:
      msg: "{{ item[0] }}{{ item[1] }}"
     with_nested:
      - [ 'calvin', 'josh', 'alice' ]
      - '{{ keys }}'         
