FROM anilkalleti/kavitha:realpage
USER root
#docker arguments
ENV JAVA_VERSION 11

#Jdk installation steps
RUN  yum install -y  java-11-openjdk-devel java-11-openjdk
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk 
   
 


   



